export const MODIFICA_EMAIL = 'MODIFICA_EMAIL';
export const MODIFICA_SENHA = 'MODIFICA_SENHA';
export const MODIFICA_NOME = 'MODIFICA_NOME';
export const MODIFICA_SOBRENOME = 'MODIFICA_SOBRENOME';
export const MODIFICA_ENDERECO = 'MODIFICA_ENDERECO';
export const MOSTRA_LISTA_ENDERECO = 'MOSTRA_LISTA_ENDERECO';
export const POPULA_ENDERECO_CADASTRO = 'POPULA_ENDERECO_CADASTRO';
export const SELECIONA_ENDERECO_LISTA_CADASTRO = 'SELECIONA_ENDERECO_LISTA_CADASTRO';
export const CONFIMAR_SOLICITACAO = 'CONFIMAR_SOLICITACAO';
export const CANCELAR_SOLICITACAO = 'CANCELAR_SOLICITACAO';
export const ON_DRAG_LOCALIZACAO = 'ON_DRAG_LOCALIZACAO';
export const ATUALIZA_TAB = 'ATUALIZA_TAB';
export const LISTA_RONDA = 'LISTA_RONDA';
export const SELECIONA_RONDA = 'SELECIONA_RONDA';



export const CADASTRO_USUARIO_SUCESSO = 'CADASTRO_USUARIO_SUCESSO';
export const CADASTRO_USUARIO_ERRO = 'CADASTRO_USUARIO_ERRO';
export const LOGIN_USUARIO_SUCESSO = 'LOGIN_USUARIO_SUCESSO';
export const LOGIN_USUARIO_ERRO = 'LOGIN_USUARIO_ERRO';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const LOADING_CADASTRO = 'LOADING_CADASTRO';
export const MODAL_VISIBLE = 'MODAL_VISIBLE';
export const MODAL_INVISIBLE = 'MODAL_INVISIBLE';


export const MODIFICA_CONTATO = 'MODIFICA_CONTATO';
export const ADICIONA_CONTATO = 'ADICIONA_CONTATO';
export const ADICIONAR_CONTATO_ERRO = 'ADICIONAR_CONTATO_ERRO';
export const ADICIONAR_CONTATO_SUCESSO = 'ADICIONAR_CONTATO_SUCESSO';
export const LISTA_USUARIO_CONTATO = 'LISTA_USUARIO_CONTATO';
export const MODIFICA_MENSAGEM = 'MODIFICA_MENSAGEM';
export const LISTA_CONVERSA_USUARIO = 'LISTA_CONVERSA_USUARIO';
export const ENVIA_MENSAGEM_SUCESSO = 'ENVIA_MENSAGEM_SUCESSO';
export const LISTA_CONVERSAS_USUARIO = 'LISTA_CONVERSAS_USUARIO';
export const GET_LOCALIZACAO_USUARIO = 'GET_LOCALIZACAO_USUARIO';
export const MODIFICA_ORIGEM = 'MODIFICA_ORIGEM';
export const MODIFICA_DESTINO = 'MODIFICA_DESTINO';
export const TOGGLE_SEARCH_RESULT = 'TOGGLE_SEARCH_RESULT';
export const GET_ENDERECO_PREDICT = 'GET_ENDERECO_PREDICT';
export const GET_ENDERECO_SELECIONADO_ORIGEM = 'GET_ENDERECO_SELECIONADO_ORIGEM';
export const GET_ENDERECO_SELECIONADO_DESTINO = 'GET_ENDERECO_SELECIONADO_DESTINO';
export const GET_DISTANCIA_MATRIX = 'GET_DISTANCIA_MATRIX';
export const GET_LOCALIZACAO_CASA = 'GET_LOCALIZACAO_CASA';
export const ATUALIZA_ROTA = 'ATUALIZA_ROTA';
export const ATUALIZA_ROTA_VIGIA = 'ATUALIZA_ROTA_VIGIA';